In [221]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [222]:
df = pd.read_csv('fmcg_customer_purchase_dataset.csv')
df.head()

,Customer_ID,Customer_Age,Gender,City,Income_Level,Product_Category,Product_Price,Discount_Percentage,Competitor_Price,Brand_Loyalty_Score,Previous_Purchases,Avg_Monthly_Spend,App_Usage_Hours,Delivery_Time_Minutes,Stock_Availability,Ad_Clicked,Festival_Season,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition,Session_Duration_Minutes,Customer_Rating,Product_Return_Rate,Coupon_Used,Wishlist_Count,Review_Count,Random_Noise_1,Random_Noise_2,Lucky_Number,Will_Buy,Quantity
0,CUST_100000,56,Male,Chennai,161867,Household,1902.41,42,2241.98,8.02,7,48997.07,1.01,69,1,0,0,Credit Card,Silver,iPhone,Safari,Morning,Sunny,22.62,2.8,0.31,0,19,319,2528,guess,3,1,4
1,CUST_100001,54,Female,Chennai,18890,Snacks,1367.01,8,1285.77,1.59,9,6956.47,8.29,11,1,0,0,UPI,Silver,iPhone,Chrome,Afternoon,Humid,2.85,4.4,0.18,0,3,269,8629,laugh,87,0,0
2,CUST_100002,57,Male,Bangalore,235884,Frozen Food,789.58,17,780.27,5.86,6,46749.97,4.23,72,1,1,1,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy,19.35,2.3,0.29,1,2,448,9110,skin,78,1,3
3,CUST_100003,20,Male,Mumbai,199064,Personal Care,1449.02,54,1554.43,7.94,4,12142.95,4.46,105,1,0,0,UPI,Bronze,Tablet,Chrome,Evening,Cloudy,52.95,3.5,0.12,0,11,43,6450,himself,92,1,6
4,CUST_100004,42,Female,Chennai,59262,Household,1815.52,0,1757.72,3.05,6,5449.31,11.37,41,1,1,0,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy,36.96,3.0,0.02,0,0,384,6249,section,53,1,2

In [223]:
df.isnull().sum()

Customer_ID                 0
Customer_Age                0
Gender                      0
City                        0
Income_Level                0
Product_Category            0
Product_Price               0
Discount_Percentage         0
Competitor_Price            0
Brand_Loyalty_Score         0
Previous_Purchases          0
Avg_Monthly_Spend           0
App_Usage_Hours             0
Delivery_Time_Minutes       0
Stock_Availability          0
Ad_Clicked                  0
Festival_Season             0
Payment_Mode                0
Membership_Level            0
Device_Type                 0
Browser_Type                0
Time_Slot                   0
Weather_Condition           0
Session_Duration_Minutes    0
Customer_Rating             0
Product_Return_Rate         0
Coupon_Used                 0
Wishlist_Count              0
Review_Count                0
Random_Noise_1              0
Random_Noise_2              0
Lucky_Number                0
Will_Buy                    0
Quantity                    0
dtype: int64

In [224]:
df.select_dtypes(include=['object'])

,Customer_ID,Gender,City,Product_Category,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition,Random_Noise_2
0,CUST_100000,Male,Chennai,Household,Credit Card,Silver,iPhone,Safari,Morning,Sunny,guess
1,CUST_100001,Female,Chennai,Snacks,UPI,Silver,iPhone,Chrome,Afternoon,Humid,laugh
2,CUST_100002,Male,Bangalore,Frozen Food,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy,skin
3,CUST_100003,Male,Mumbai,Personal Care,UPI,Bronze,Tablet,Chrome,Evening,Cloudy,himself
4,CUST_100004,Female,Chennai,Household,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy,section
...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST_149995,Male,Bangalore,Beverages,Wallet,Bronze,Desktop,Edge,Morning,Rainy,relationship
49996,CUST_149996,Female,Bangalore,Dairy,UPI,Gold,Tablet,Firefox,Evening,Humid,decision
49997,CUST_149997,Female,Hyderabad,Beverages,Wallet,Gold,Tablet,Safari,Night,Rainy,country
49998,CUST_149998,Female,Hyderabad,Frozen Food,Cash,Gold,iPhone,Firefox,Evening,Humid,stuff
49999,CUST_149999,Female,Kolkata,Beverages,Wallet,Gold,Android,Firefox,Morning,Cloudy,other

In [225]:
df = df.drop(['Customer_ID','Random_Noise_2'],axis=1)

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_Age              50000 non-null  int64
 1   Gender                    50000 non-null  object
 2   City                      50000 non-null  object
 3   Income_Level              50000 non-null  int64
 4   Product_Category          50000 non-null  object
 5   Product_Price             50000 non-null  float64
 6   Discount_Percentage       50000 non-null  int64
 7   Competitor_Price          50000 non-null  float64
 8   Brand_Loyalty_Score       50000 non-null  float64
 9   Previous_Purchases        50000 non-null  int64
 10  Avg_Monthly_Spend         50000 non-null  float64
 11  App_Usage_Hours           50000 non-null  float64
 12  Delivery_Time_Minutes     50000 non-null  int64
 13  Stock_Availability        50000 non-null  int64
 14  Ad_Clicked                50000 non-null  int64
 15  Festival_Season           50000 non-null  int64
 16  Payment_Mode              50000 non-null  object
 17  Membership_Level          50000 non-null  object
 18  Device_Type               50000 non-null  object
 19  Browser_Type              50000 non-null  object
 20  Time_Slot                 50000 non-null  object
 21  Weather_Condition         50000 non-null  object
 22  Session_Duration_Minutes  50000 non-null  float64
 23  Customer_Rating           50000 non-null  float64
 24  Product_Return_Rate       50000 non-null  float64
 25  Coupon_Used               50000 non-null  int64
 26  Wishlist_Count            50000 non-null  int64
 27  Review_Count              50000 non-null  int64
 28  Random_Noise_1            50000 non-null  int64
 29  Lucky_Number              50000 non-null  int64
 30  Will_Buy                  50000 non-null  int64
 31  Quantity                  50000 non-null  int64
dtypes: float64(8), int64(15), object(9)
memory usage: 12.2+ MB

In [227]:
pd.set_option('display.max_columns', None)
df.head()

,Customer_Age,Gender,City,Income_Level,Product_Category,Product_Price,Discount_Percentage,Competitor_Price,Brand_Loyalty_Score,Previous_Purchases,Avg_Monthly_Spend,App_Usage_Hours,Delivery_Time_Minutes,Stock_Availability,Ad_Clicked,Festival_Season,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition,Session_Duration_Minutes,Customer_Rating,Product_Return_Rate,Coupon_Used,Wishlist_Count,Review_Count,Random_Noise_1,Lucky_Number,Will_Buy,Quantity
0,56,Male,Chennai,161867,Household,1902.41,42,2241.98,8.02,7,48997.07,1.01,69,1,0,0,Credit Card,Silver,iPhone,Safari,Morning,Sunny,22.62,2.8,0.31,0,19,319,2528,3,1,4
1,54,Female,Chennai,18890,Snacks,1367.01,8,1285.77,1.59,9,6956.47,8.29,11,1,0,0,UPI,Silver,iPhone,Chrome,Afternoon,Humid,2.85,4.4,0.18,0,3,269,8629,87,0,0
2,57,Male,Bangalore,235884,Frozen Food,789.58,17,780.27,5.86,6,46749.97,4.23,72,1,1,1,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy,19.35,2.3,0.29,1,2,448,9110,78,1,3
3,20,Male,Mumbai,199064,Personal Care,1449.02,54,1554.43,7.94,4,12142.95,4.46,105,1,0,0,UPI,Bronze,Tablet,Chrome,Evening,Cloudy,52.95,3.5,0.12,0,11,43,6450,92,1,6
4,42,Female,Chennai,59262,Household,1815.52,0,1757.72,3.05,6,5449.31,11.37,41,1,1,0,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy,36.96,3.0,0.02,0,0,384,6249,53,1,2

In [228]:
df = df.drop(['Random_Noise_1','Quantity'],axis=1)

In [229]:
df.select_dtypes(include=['object'])

,Gender,City,Product_Category,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition
0,Male,Chennai,Household,Credit Card,Silver,iPhone,Safari,Morning,Sunny
1,Female,Chennai,Snacks,UPI,Silver,iPhone,Chrome,Afternoon,Humid
2,Male,Bangalore,Frozen Food,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy
3,Male,Mumbai,Personal Care,UPI,Bronze,Tablet,Chrome,Evening,Cloudy
4,Female,Chennai,Household,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy
...,...,...,...,...,...,...,...,...,...
49995,Male,Bangalore,Beverages,Wallet,Bronze,Desktop,Edge,Morning,Rainy
49996,Female,Bangalore,Dairy,UPI,Gold,Tablet,Firefox,Evening,Humid
49997,Female,Hyderabad,Beverages,Wallet,Gold,Tablet,Safari,Night,Rainy
49998,Female,Hyderabad,Frozen Food,Cash,Gold,iPhone,Firefox,Evening,Humid
49999,Female,Kolkata,Beverages,Wallet,Gold,Android,Firefox,Morning,Cloudy

In [230]:
df['City'].unique()

array(['Chennai', 'Bangalore', 'Mumbai', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [231]:
df['Product_Category'].unique()

array(['Household', 'Snacks', 'Frozen Food', 'Personal Care', 'Dairy',
       'Beverages'], dtype=object)

In [232]:
df.select_dtypes(include=['object'])

,Gender,City,Product_Category,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition
0,Male,Chennai,Household,Credit Card,Silver,iPhone,Safari,Morning,Sunny
1,Female,Chennai,Snacks,UPI,Silver,iPhone,Chrome,Afternoon,Humid
2,Male,Bangalore,Frozen Food,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy
3,Male,Mumbai,Personal Care,UPI,Bronze,Tablet,Chrome,Evening,Cloudy
4,Female,Chennai,Household,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy
...,...,...,...,...,...,...,...,...,...
49995,Male,Bangalore,Beverages,Wallet,Bronze,Desktop,Edge,Morning,Rainy
49996,Female,Bangalore,Dairy,UPI,Gold,Tablet,Firefox,Evening,Humid
49997,Female,Hyderabad,Beverages,Wallet,Gold,Tablet,Safari,Night,Rainy
49998,Female,Hyderabad,Frozen Food,Cash,Gold,iPhone,Firefox,Evening,Humid
49999,Female,Kolkata,Beverages,Wallet,Gold,Android,Firefox,Morning,Cloudy

In [233]:
df.head()

,Customer_Age,Gender,City,Income_Level,Product_Category,Product_Price,Discount_Percentage,Competitor_Price,Brand_Loyalty_Score,Previous_Purchases,Avg_Monthly_Spend,App_Usage_Hours,Delivery_Time_Minutes,Stock_Availability,Ad_Clicked,Festival_Season,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition,Session_Duration_Minutes,Customer_Rating,Product_Return_Rate,Coupon_Used,Wishlist_Count,Review_Count,Lucky_Number,Will_Buy
0,56,Male,Chennai,161867,Household,1902.41,42,2241.98,8.02,7,48997.07,1.01,69,1,0,0,Credit Card,Silver,iPhone,Safari,Morning,Sunny,22.62,2.8,0.31,0,19,319,3,1
1,54,Female,Chennai,18890,Snacks,1367.01,8,1285.77,1.59,9,6956.47,8.29,11,1,0,0,UPI,Silver,iPhone,Chrome,Afternoon,Humid,2.85,4.4,0.18,0,3,269,87,0
2,57,Male,Bangalore,235884,Frozen Food,789.58,17,780.27,5.86,6,46749.97,4.23,72,1,1,1,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy,19.35,2.3,0.29,1,2,448,78,1
3,20,Male,Mumbai,199064,Personal Care,1449.02,54,1554.43,7.94,4,12142.95,4.46,105,1,0,0,UPI,Bronze,Tablet,Chrome,Evening,Cloudy,52.95,3.5,0.12,0,11,43,92,1
4,42,Female,Chennai,59262,Household,1815.52,0,1757.72,3.05,6,5449.31,11.37,41,1,1,0,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy,36.96,3.0,0.02,0,0,384,53,1

In [234]:
df.select_dtypes(include=['object'])

,Gender,City,Product_Category,Payment_Mode,Membership_Level,Device_Type,Browser_Type,Time_Slot,Weather_Condition
0,Male,Chennai,Household,Credit Card,Silver,iPhone,Safari,Morning,Sunny
1,Female,Chennai,Snacks,UPI,Silver,iPhone,Chrome,Afternoon,Humid
2,Male,Bangalore,Frozen Food,Credit Card,Bronze,iPhone,Edge,Evening,Cloudy
3,Male,Mumbai,Personal Care,UPI,Bronze,Tablet,Chrome,Evening,Cloudy
4,Female,Chennai,Household,Debit Card,Bronze,Tablet,Chrome,Evening,Cloudy
...,...,...,...,...,...,...,...,...,...
49995,Male,Bangalore,Beverages,Wallet,Bronze,Desktop,Edge,Morning,Rainy
49996,Female,Bangalore,Dairy,UPI,Gold,Tablet,Firefox,Evening,Humid
49997,Female,Hyderabad,Beverages,Wallet,Gold,Tablet,Safari,Night,Rainy
49998,Female,Hyderabad,Frozen Food,Cash,Gold,iPhone,Firefox,Evening,Humid
49999,Female,Kolkata,Beverages,Wallet,Gold,Android,Firefox,Morning,Cloudy

In [235]:
cols_to_drop = [
    'Lucky_Number',
    'Browser_Type',
    'Device_Type',
    'Weather_Condition',
    'Time_Slot'
]

df.drop(cols_to_drop, axis=1, inplace=True)

In [236]:
from sklearn.preprocessing import OneHotEncoder
categorical_cols = [
    'Gender',
    'City',
    'Product_Category',
    'Payment_Mode',
    'Membership_Level'
]

encoder = OneHotEncoder(
    handle_unknown='ignore'
)

encoded = encoder.fit_transform(
    df[categorical_cols]
).toarray()

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=df.index
)

df = pd.concat(
    [df.drop(categorical_cols, axis=1), encoded_df],
    axis=1
)

In [237]:
X = df.drop('Will_Buy',axis=1)
y = df['Will_Buy']

In [238]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [239]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train_smote,y_train_smote= smote.fit_resample(X_train,y_train)

In [240]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_smote)
X_test_scaled = scaler.transform(X_test)

In [241]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_train_scaled,y_train_smote)
y_pred = log.predict(X_test_scaled)

In [242]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision Score:",precision_score(y_test,y_pred))
print("Recall Score:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))

Accuracy: 0.9577333333333333
Precision Score: 0.9960862449299082
Recall Score: 0.960279892982095
F1 Score: 0.9778553964373036

In [243]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  368    55]
 [  579 13998]]

In [244]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier()
forest.fit(X_train_scaled,y_train_smote)
y_pred = forest.predict(X_test_scaled)

In [245]:
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision Score:",precision_score(y_test,y_pred))
print("Recall Score:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9757333333333333
Precision Score: 0.9769143010536205
Recall Score: 0.9986279755779652
F1 Score: 0.9876518081280955
[[   79   344]
 [   20 14557]]

In [246]:
from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(X_train_scaled,y_train_smote)
y_pred = xgb.predict(X_test_scaled)

In [247]:
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision Score:",precision_score(y_test,y_pred))
print("Recall Score:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9784666666666667
Precision Score: 0.9845662224639652
Recall Score: 0.9934142827742334
F1 Score: 0.9889704626942121
[[  196   227]
 [   96 14481]]

In [248]:
importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': xgb.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

importance.head(20)

                         Feature  Importance
12               Festival_Season    0.193604
5            Brand_Loyalty_Score    0.143214
11                    Ad_Clicked    0.094482
10            Stock_Availability    0.058547
20                   Gender_Male    0.054130
36              Payment_Mode_UPI    0.036524
40     Membership_Level_Platinum    0.023386
39         Membership_Level_Gold    0.022924
29  Product_Category_Frozen Food    0.021932
32       Product_Category_Snacks    0.021260
19                 Gender_Female    0.020809
38       Membership_Level_Bronze    0.019193
33             Payment_Mode_Cash    0.019011
30    Product_Category_Household    0.018828
27    Product_Category_Beverages    0.018299
26                   City_Mumbai    0.017963
6             Previous_Purchases    0.017766
34      Payment_Mode_Credit Card    0.017470
41       Membership_Level_Silver    0.017340
22                  City_Chennai    0.017172

In [249]:
df.head(1)

,Customer_Age,Income_Level,Product_Price,Discount_Percentage,Competitor_Price,Brand_Loyalty_Score,Previous_Purchases,Avg_Monthly_Spend,App_Usage_Hours,Delivery_Time_Minutes,Stock_Availability,Ad_Clicked,Festival_Season,Session_Duration_Minutes,Customer_Rating,Product_Return_Rate,Coupon_Used,Wishlist_Count,Review_Count,Will_Buy,Gender_Female,Gender_Male,City_Bangalore,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Product_Category_Beverages,Product_Category_Dairy,Product_Category_Frozen Food,Product_Category_Household,Product_Category_Personal Care,Product_Category_Snacks,Payment_Mode_Cash,Payment_Mode_Credit Card,Payment_Mode_Debit Card,Payment_Mode_UPI,Payment_Mode_Wallet,Membership_Level_Bronze,Membership_Level_Gold,Membership_Level_Platinum,Membership_Level_Silver
0,56,161867,1902.41,42,2241.98,8.02,7,48997.07,1.01,69,1,0,0,22.62,2.8,0.31,0,19,319,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [250]:
import joblib

joblib.dump(xgb, 'xgb_model.pkl')
joblib.dump(encoder, 'encoder.pkl')
feature_columns = X.columns
joblib.dump(feature_columns,'feature_columns.pkl')

['feature_columns.pkl']

In [251]:
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']